### ISSUE TITLE
loop

### ISSUE THREAD

**Issue by NightsProject** [xbryan25/Simple_Cafeteria#1]
After starting the prog, and inputting letter/s instead of the 3 choices of numbers, it will have an output of "Invalid Option" and the program loops or run abnormally.

**Comment by xbryan25** [comment]
Cause of the problem: When a user inputs a character in the main screen, instead of a number, the _choice_ variable won't have any value. scanf() will be ignored in the subsequent iterations of the while loop, therefore making the program run indefinitely and abnormally.

Status: Fixed

Reference: [https://www.youtube.com/watch?v=xYg7hdN-9uc](url)
